apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeting-app2-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: greeting-app2
  template:
    metadata:
      labels:
        app: greeting-app2
    spec:
      containers:
        - name: greeting-app2
          image: rakholiya5500/greeting-app2:latest
